// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/route_guide.proto
// Protobuf Java Version: 4.29.3

package com.yd.scala.grpc.routeguide;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<com.yd.scala.grpc.routeguide.Feature> 
      getFeatureList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  com.yd.scala.grpc.routeguide.Feature getFeature(int index);
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<? extends com.yd.scala.grpc.routeguide.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  com.yd.scala.grpc.routeguide.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
