// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/route_guide.proto
// Protobuf Java Version: 4.29.3

package com.yd.scala.grpc.routeguide;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   * @return The longitude.
   */
  int getLongitude();
}
