// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/route_guide.proto
// Protobuf Java Version: 4.29.3

package com.yd.scala.grpc.routeguide;

/**
 * <pre>
 * A latitude-longitude rectangle, represented as two diagonally opposite
 * points "lo" and "hi".
 * </pre>
 *
 * Protobuf type {@code Rectangle}
 */
public final class Rectangle extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Rectangle)
    RectangleOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Rectangle.class.getName());
  }
  // Use Rectangle.newBuilder() to construct.
  private Rectangle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Rectangle() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yd.scala.grpc.routeguide.RouteGuideProto.internal_static_Rectangle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yd.scala.grpc.routeguide.RouteGuideProto.internal_static_Rectangle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yd.scala.grpc.routeguide.Rectangle.class, com.yd.scala.grpc.routeguide.Rectangle.Builder.class);
  }

  private int bitField0_;
  public static final int LO_FIELD_NUMBER = 1;
  private com.yd.scala.grpc.routeguide.Point lo_;
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   * @return Whether the lo field is set.
   */
  @java.lang.Override
  public boolean hasLo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   * @return The lo.
   */
  @java.lang.Override
  public com.yd.scala.grpc.routeguide.Point getLo() {
    return lo_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : lo_;
  }
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   */
  @java.lang.Override
  public com.yd.scala.grpc.routeguide.PointOrBuilder getLoOrBuilder() {
    return lo_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : lo_;
  }

  public static final int HI_FIELD_NUMBER = 2;
  private com.yd.scala.grpc.routeguide.Point hi_;
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   * @return Whether the hi field is set.
   */
  @java.lang.Override
  public boolean hasHi() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   * @return The hi.
   */
  @java.lang.Override
  public com.yd.scala.grpc.routeguide.Point getHi() {
    return hi_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : hi_;
  }
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   */
  @java.lang.Override
  public com.yd.scala.grpc.routeguide.PointOrBuilder getHiOrBuilder() {
    return hi_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : hi_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getHi());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHi());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yd.scala.grpc.routeguide.Rectangle)) {
      return super.equals(obj);
    }
    com.yd.scala.grpc.routeguide.Rectangle other = (com.yd.scala.grpc.routeguide.Rectangle) obj;

    if (hasLo() != other.hasLo()) return false;
    if (hasLo()) {
      if (!getLo()
          .equals(other.getLo())) return false;
    }
    if (hasHi() != other.hasHi()) return false;
    if (hasHi()) {
      if (!getHi()
          .equals(other.getHi())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLo()) {
      hash = (37 * hash) + LO_FIELD_NUMBER;
      hash = (53 * hash) + getLo().hashCode();
    }
    if (hasHi()) {
      hash = (37 * hash) + HI_FIELD_NUMBER;
      hash = (53 * hash) + getHi().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yd.scala.grpc.routeguide.Rectangle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yd.scala.grpc.routeguide.Rectangle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yd.scala.grpc.routeguide.Rectangle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yd.scala.grpc.routeguide.Rectangle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A latitude-longitude rectangle, represented as two diagonally opposite
   * points "lo" and "hi".
   * </pre>
   *
   * Protobuf type {@code Rectangle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Rectangle)
      com.yd.scala.grpc.routeguide.RectangleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yd.scala.grpc.routeguide.RouteGuideProto.internal_static_Rectangle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yd.scala.grpc.routeguide.RouteGuideProto.internal_static_Rectangle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yd.scala.grpc.routeguide.Rectangle.class, com.yd.scala.grpc.routeguide.Rectangle.Builder.class);
    }

    // Construct using com.yd.scala.grpc.routeguide.Rectangle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLoFieldBuilder();
        getHiFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lo_ = null;
      if (loBuilder_ != null) {
        loBuilder_.dispose();
        loBuilder_ = null;
      }
      hi_ = null;
      if (hiBuilder_ != null) {
        hiBuilder_.dispose();
        hiBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yd.scala.grpc.routeguide.RouteGuideProto.internal_static_Rectangle_descriptor;
    }

    @java.lang.Override
    public com.yd.scala.grpc.routeguide.Rectangle getDefaultInstanceForType() {
      return com.yd.scala.grpc.routeguide.Rectangle.getDefaultInstance();
    }

    @java.lang.Override
    public com.yd.scala.grpc.routeguide.Rectangle build() {
      com.yd.scala.grpc.routeguide.Rectangle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yd.scala.grpc.routeguide.Rectangle buildPartial() {
      com.yd.scala.grpc.routeguide.Rectangle result = new com.yd.scala.grpc.routeguide.Rectangle(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yd.scala.grpc.routeguide.Rectangle result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lo_ = loBuilder_ == null
            ? lo_
            : loBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hi_ = hiBuilder_ == null
            ? hi_
            : hiBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yd.scala.grpc.routeguide.Rectangle) {
        return mergeFrom((com.yd.scala.grpc.routeguide.Rectangle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yd.scala.grpc.routeguide.Rectangle other) {
      if (other == com.yd.scala.grpc.routeguide.Rectangle.getDefaultInstance()) return this;
      if (other.hasLo()) {
        mergeLo(other.getLo());
      }
      if (other.hasHi()) {
        mergeHi(other.getHi());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getHiFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.yd.scala.grpc.routeguide.Point lo_;
    private com.google.protobuf.SingleFieldBuilder<
        com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder> loBuilder_;
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     * @return Whether the lo field is set.
     */
    public boolean hasLo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     * @return The lo.
     */
    public com.yd.scala.grpc.routeguide.Point getLo() {
      if (loBuilder_ == null) {
        return lo_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : lo_;
      } else {
        return loBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public Builder setLo(com.yd.scala.grpc.routeguide.Point value) {
      if (loBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lo_ = value;
      } else {
        loBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public Builder setLo(
        com.yd.scala.grpc.routeguide.Point.Builder builderForValue) {
      if (loBuilder_ == null) {
        lo_ = builderForValue.build();
      } else {
        loBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public Builder mergeLo(com.yd.scala.grpc.routeguide.Point value) {
      if (loBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          lo_ != null &&
          lo_ != com.yd.scala.grpc.routeguide.Point.getDefaultInstance()) {
          getLoBuilder().mergeFrom(value);
        } else {
          lo_ = value;
        }
      } else {
        loBuilder_.mergeFrom(value);
      }
      if (lo_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public Builder clearLo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lo_ = null;
      if (loBuilder_ != null) {
        loBuilder_.dispose();
        loBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public com.yd.scala.grpc.routeguide.Point.Builder getLoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    public com.yd.scala.grpc.routeguide.PointOrBuilder getLoOrBuilder() {
      if (loBuilder_ != null) {
        return loBuilder_.getMessageOrBuilder();
      } else {
        return lo_ == null ?
            com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : lo_;
      }
    }
    /**
     * <pre>
     * One corner of the rectangle.
     * </pre>
     *
     * <code>.Point lo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder> 
        getLoFieldBuilder() {
      if (loBuilder_ == null) {
        loBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder>(
                getLo(),
                getParentForChildren(),
                isClean());
        lo_ = null;
      }
      return loBuilder_;
    }

    private com.yd.scala.grpc.routeguide.Point hi_;
    private com.google.protobuf.SingleFieldBuilder<
        com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder> hiBuilder_;
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     * @return Whether the hi field is set.
     */
    public boolean hasHi() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     * @return The hi.
     */
    public com.yd.scala.grpc.routeguide.Point getHi() {
      if (hiBuilder_ == null) {
        return hi_ == null ? com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : hi_;
      } else {
        return hiBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public Builder setHi(com.yd.scala.grpc.routeguide.Point value) {
      if (hiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hi_ = value;
      } else {
        hiBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public Builder setHi(
        com.yd.scala.grpc.routeguide.Point.Builder builderForValue) {
      if (hiBuilder_ == null) {
        hi_ = builderForValue.build();
      } else {
        hiBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public Builder mergeHi(com.yd.scala.grpc.routeguide.Point value) {
      if (hiBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          hi_ != null &&
          hi_ != com.yd.scala.grpc.routeguide.Point.getDefaultInstance()) {
          getHiBuilder().mergeFrom(value);
        } else {
          hi_ = value;
        }
      } else {
        hiBuilder_.mergeFrom(value);
      }
      if (hi_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public Builder clearHi() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hi_ = null;
      if (hiBuilder_ != null) {
        hiBuilder_.dispose();
        hiBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public com.yd.scala.grpc.routeguide.Point.Builder getHiBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getHiFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    public com.yd.scala.grpc.routeguide.PointOrBuilder getHiOrBuilder() {
      if (hiBuilder_ != null) {
        return hiBuilder_.getMessageOrBuilder();
      } else {
        return hi_ == null ?
            com.yd.scala.grpc.routeguide.Point.getDefaultInstance() : hi_;
      }
    }
    /**
     * <pre>
     * The other corner of the rectangle.
     * </pre>
     *
     * <code>.Point hi = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder> 
        getHiFieldBuilder() {
      if (hiBuilder_ == null) {
        hiBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yd.scala.grpc.routeguide.Point, com.yd.scala.grpc.routeguide.Point.Builder, com.yd.scala.grpc.routeguide.PointOrBuilder>(
                getHi(),
                getParentForChildren(),
                isClean());
        hi_ = null;
      }
      return hiBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Rectangle)
  }

  // @@protoc_insertion_point(class_scope:Rectangle)
  private static final com.yd.scala.grpc.routeguide.Rectangle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yd.scala.grpc.routeguide.Rectangle();
  }

  public static com.yd.scala.grpc.routeguide.Rectangle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rectangle>
      PARSER = new com.google.protobuf.AbstractParser<Rectangle>() {
    @java.lang.Override
    public Rectangle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rectangle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rectangle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yd.scala.grpc.routeguide.Rectangle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

