// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/route_guide.proto
// Protobuf Java Version: 4.29.3

package com.yd.scala.grpc.routeguide;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RouteGuideProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FeatureDatabase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RouteNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RouteSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/route_guide.proto\",\n\005Po" +
      "int\022\020\n\010latitude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005" +
      "\"3\n\tRectangle\022\022\n\002lo\030\001 \001(\0132\006.Point\022\022\n\002hi\030" +
      "\002 \001(\0132\006.Point\"1\n\007Feature\022\014\n\004name\030\001 \001(\t\022\030" +
      "\n\010location\030\002 \001(\0132\006.Point\",\n\017FeatureDatab" +
      "ase\022\031\n\007feature\030\001 \003(\0132\010.Feature\"6\n\tRouteN" +
      "ote\022\030\n\010location\030\001 \001(\0132\006.Point\022\017\n\007message" +
      "\030\002 \001(\t\"b\n\014RouteSummary\022\023\n\013point_count\030\001 " +
      "\001(\005\022\025\n\rfeature_count\030\002 \001(\005\022\020\n\010distance\030\003" +
      " \001(\005\022\024\n\014elapsed_time\030\004 \001(\0052\255\001\n\nRouteGuid" +
      "e\022 \n\nGetFeature\022\006.Point\032\010.Feature\"\000\022(\n\014L" +
      "istFeatures\022\n.Rectangle\032\010.Feature\"\0000\001\022(\n" +
      "\013RecordRoute\022\006.Point\032\r.RouteSummary\"\000(\001\022" +
      ")\n\tRouteChat\022\n.RouteNote\032\n.RouteNote\"\000(\001" +
      "0\001B7\n\034com.yd.scala.grpc.routeguideB\017Rout" +
      "eGuideProtoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Rectangle_descriptor,
        new java.lang.String[] { "Lo", "Hi", });
    internal_static_Feature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Feature_descriptor,
        new java.lang.String[] { "Name", "Location", });
    internal_static_FeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FeatureDatabase_descriptor,
        new java.lang.String[] { "Feature", });
    internal_static_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RouteNote_descriptor,
        new java.lang.String[] { "Location", "Message", });
    internal_static_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RouteSummary_descriptor,
        new java.lang.String[] { "PointCount", "FeatureCount", "Distance", "ElapsedTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
